schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "PublicEnvironmentInput"
  types:
    PublicEnvironmentInput:
      type: object
      description: "Input properties for my environment"
      properties:
        vpc_to_be_used:
          title: "VPC ID for environment"
          type: string
          description: "Choose the VPC where the cluster will be deployed"
        subnet_one_cidr:
          title: "Subnet one ID"
          type: string
          description: "The first subnet ID"
        subnet_two_cidr:
          title: "Subnet two ID"
          type: string
          description: "The second subnet ID"