schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "PublicEnvironmentInput"
  types:
    PublicEnvironmentInput:
      type: object
      description: "Input properties for my environment"
      properties:
        vpc_cidr:
          title: "VPC to use"
          type: "List<AWS::EC2::VPC::Id>"
          description: "Choose the VPC where the cluster will be deployed"
